#!/bin/bash
for var_lb in /mnt/e/wd/sequence_reads/*; do
	for var_dir in ${var_lb}/fastq/*; do
		for var_fastq in ${var_dir}/*; do
			if [[ ${var_fastq} = *"_R1_"* ]]; then
				var_sm=$(echo "$var_fastq" | grep -Po "(N|P|AG|GM)-?\d{2,}")
				var_lb1=$(echo "$var_lb" | grep -Po "\d{8}")
				var_lb2=$(echo "$var_dir" | cut -d / -f 8)
				var_r2=${var_fastq/R1/R2}
				
				# Align sequence
				if [ ! -s "/mnt/e/wd/pipeline/1_sam/${var_sm}.sam" ]; then
					bwa mem -t 4 -M -R "@RG\tID:MJ\tLB:${var_lb1}-${var_lb2}\tPL:ILLUMINA\tSM:${var_sm}" \
						/mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
						${var_fastq} \
						${var_r2} \
						> /mnt/e/wd/pipeline/1_sam/${var_sm}.sam
				fi
				
				# sam to bam
				if [ ! -s "/mnt/e/wd/pipeline/2_sam/${var_sm}.bam" ]; then
				# if test $? = 0; then
					samtools view -Sb -h -@ 4 \
						/mnt/e/wd/pipeline/1_sam/${var_sm}.sam \
						-o /mnt/e/wd/pipeline/2_bam/${var_sm}.bam
				fi

				# Sort aligned sequence
				if [ ! -s "/mnt/e/wd/pipeline/3_sorted.bam/${var_sm}.sorted.bam" ]; then
				# if test $? = 0; then
					samtools sort -@ 4 \
						/mnt/e/wd/pipeline/2_bam/${var_sm}.bam \
						-o /mnt/e/wd/pipeline/3_sorted.bam/${var_sm}.sorted.bam
				fi

				# Mark duplicates
				if [ ! -s "/mnt/e/wd/pipeline/4_marked_dup/${var_sm}.marked_dup.bam" \
					-a ! -s "/mnt/e/wd/pipeline/4_marked_dup/${var_sm}.marked_dup_metrics.txt" ]; then
				# if test $? = 0; then
					java -jar /home/lee/wd/program/picard/picard.jar MarkDuplicates \
						-I /mnt/e/wd/pipeline/3_sorted.bam/${var_sm}.sorted.bam \
						-O /mnt/e/wd/pipeline/4_marked_dup/${var_sm}.marked_dup.bam \
						-M /mnt/e/wd/pipeline/4_marked_dup/${var_sm}.marked_dup_metrics.txt
				fi

				# Sortsam
				if [ ! -s "/mnt/e/wd/pipeline/5_sortsam/${var_sm}.sortsam.bam" ]; then 				
				# if test $? = 0; then
					java -jar /home/lee/wd/program/picard/picard.jar SortSam \
						-I /mnt/e/wd/pipeline/4_marked_dup/${var_sm}.marked_dup.bam \
						-O /mnt/e/wd/pipeline/5_sortsam/${var_sm}.sortsam.bam \
						-SO coordinate
				fi

				# Base recalibration
				if [ ! -s "/mnt/e/wd/pipeline/6_bqsr/${var_sm}.recal_data.table" ]; then 
				# if test $? = 0; then
					/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" BaseRecalibrator \
						-I /mnt/e/wd/pipeline/5_sortsam/${var_sm}.sortsam.bam \
						-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
						--known-sites /mnt/e/wd/resource_bundle/dbsnp_138.b37.vcf \
						--known-sites /mnt/e/wd/resource_bundle/Mills_and_1000G_gold_standard.indels.b37.vcf \
						--known-sites /mnt/e/wd/resource_bundle/1000G_phase1.indels.b37.vcf \
						-O /mnt/e/wd/pipeline/6_bqsr/${var_sm}.recal_data.table
				fi

				# Apply recalibration
				if [ ! -s "/mnt/e/wd/pipeline/7_output.bam/${var_sm}.output.bam" ]; then 
				# if test $? = 0; then
					/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" ApplyBQSR \
						-I /mnt/e/wd/pipeline/5_sortsam/${var_sm}.sortsam.bam \
						-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
						--bqsr-recal-file /mnt/e/wd/pipeline/6_bqsr/${var_sm}.recal_data.table \
						-O /mnt/e/wd/pipeline/7_output.bam/${var_sm}.output.bam
				fi

				# HaplotypeCaller
				if [ ! -s "/mnt/e/wd/pipeline/8_gvcf/${var_sm}.g.vcf.gz" ]; then 
				# if test $? = 0; then
					/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" HaplotypeCaller \
						-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
						-I /mnt/e/wd/pipeline/7_output.bam/${var_sm}.output.bam \
						-O /mnt/e/wd/pipeline/8_gvcf/${var_sm}.g.vcf.gz \
						-ERC GVCF
				fi
			fi
		done
	done
done
