#! /bin/bash
for var_lb in /mnt/e/wd/sequence_reads/*; do
	for var_dir in ${var_lb}/fastq/*; do
		for var_fastq in ${var_dir}/*; do
			if [[ ${var_fastq} = *"_R1_"* ]]; then
				var_sm = grep N|P-?\d+ var_fastq
				bwa mem -t 4 -M- R '@RG\t:MJ\tLB:${var_lib}${var_dir}\tPL:ILLUMINA\tSM:${var_sm}' \
				${var_fastq} \
				sed \
				> /mnt/e/wd/sam/${var_sm}.sam

				samtools view -Sb -h -@ 4 \
				/mnt/e/wd/sam/${var_sm}.sam \
				-o /mnt/e/wd/bam/${var_sm}.bam

				samtools sort -@ 4 \
				/mnt/e/wd/bam/${var_sm}.bam
				-o /mnt/e/wd/bam/sorted.bam/${var_sm}.sorted.bam

				samtools index -b -@ 4 \
				/mnt/e/wd/bam/sorted.bam/${var_sm}.sorted.bam

				java -jar /home/lee/wd/program/picard/picard.jar MarkDuplicates \
				-I /mnt/e/wd/bam/sorted.bam/${var_sm}.sorted.bam \
				-O /mnt/e/wd/bam/marked_dup/${var_sm}.marked_dup.bam \
				-M /mnt/e/wd/bam/marked_dup/${var_sm}.marked_dup_metrics.txt

				java -jar /home/lee/wd/program/picard/picard.jar SortSam \
				-I /mnt/e/wd/bam/marked_dup/${var_sm}.marked_dup.bam \
				-O /mnt/e/wd/bam/sortsam/${var_sm}.sortsam.bam \
				-SO coordinate

				/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" BaseRecalibrator \
				-I /mnt/e/wd/bam/sortsam/${var_sam}.bam \
				-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
				--known-sites /mnt/e/wd/resource_bundle/dbsnp_138.b37.vcf \
				--known-sites /mnt/e/wd/resource_bundle/Mills_and_1000G_gold_standard.indels.b37.vcf \
				--known-sites /mnt/e/wd/resource_bundle/1000G_phase1.snps.high_confidence.b37.vcf \
				--known-sites /mnt/e/wd/resource_bundle/1000G_phase1.indels.b37.vcf \
				-O /mnt/wd/bqsr/${var_sam}.recal_data.table

				/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" ApplyBQSR \
				-I /mnt/e/wd/bam/sortsam/${var_sam}.sortsam.bam \
				-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
				--sqsr-recal-file /mnt/e/wd/bqsr/${var_sam}.recal_data.table \
				-O /mnt/e/wd/bam/output/${var_sam}.output.bam
				
				/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" HaplotypeCaller \
				-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
				-I /mnt/e/wd/bam/output/${var_sm}.output.bam \
				-O /mnt/e/wd/gvcf/${var_sm}.g.vcf.gz \
				-ERC GCVF
		done
	done
done
