#! /bin/bash
for var_lb in /mnt/e/wd/sequence_reads/*; do
	for var_dir in ${var_lb}/fastq/*; do
		for var_fastq in ${var_dir}/*; do
			if [[ ${var_fastq} = *"_R1_"* ]]; then
				var_sm=$(echo "$var_fastq" | grep -Po "(N|P|AG|GM)-?\d{2,}")
				var_lb1=$(echo "$var_lb" | grep -Po "\d{8}")
				var_lb2=$(echo "$var_dir" | cut -d / -f 8)
				var_r2=${var_fastq/R1/R2}
				
				# Align sequence
				bwa mem -t 4 -M -R "@RG\tID:MJ\tLB:${var_lb1}-${var_lb2}\tPL:ILLUMINA\tSM:${var_sm}" \
				${var_fastq} \
				${var_r2} \
				> /mnt/e/wd/pipeline/1_sam/${var_sm}.sam

				# Sort aligned sequence
				if (); then
					samtools sort -@ 4 \
					/mnt/e/wd/pipeline/1_sam/${var_sm}.sam
					-o /mnt/e/wd/bam/2_sorted.bam/${var_sm}.sorted.bam
				fi

				# Mark duplicates
				java -jar /home/lee/wd/program/picard/picard.jar MarkDuplicates \
				-I /mnt/e/wd/pipeline/2_sorted.bam/sorted.bam/${var_sm}.sorted.bam \
				-O /mnt/e/wd/pipeline/3_marked_dup/${var_sm}.marked_dup.bam \
				-M /mnt/e/wd/pipeline/3_marked_dup/${var_sm}.marked_dup_metrics.txt

				# Sortsam
				java -jar program/picard/picard.jar SortSam \
				-I /mnt/e/wd/pipeline/marked_dup/${var_sm}.marked_dup.bam \
				-O /mnt/e/wd/pipeline/sortsam/${var_sm}.sortsam.bam \
				-SO coordinate

				# Base recalibration
				/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" BaseRecalibrator \
				-I /mnt/e/wd/pipeline/4_sortsam/${var_sam}.sortsam.bam \
				-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
				--known-sites /mnt/e/wd/resource_bundle/dbsnp_138.b37.vcf \
				--known-sites /mnt/e/wd/resource_bundle/Mills_and_1000G_gold_standard.indels.b37.vcf \
				--known-sites /mnt/e/wd/resource_bundle/1000G_phase1.snps.high_confidence.b37.vcf \
				--known-sites /mnt/e/wd/resource_bundle/1000G_phase1.indels.b37.vcf \
				-O /mnt/wd/pipeline/4_bqsr/${var_sam}.recal_data.table

				# Apply recalibration
				/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" ApplyBQSR \
				-I /mnt/e/wd/pipeline/4_sortsam/${var_sam}.sortsam.bam \
				-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
				--sqsr-recal-file /mnt/e/wd/pipeline/5_bqsr/${var_sam}.recal_data.table \
				-O /mnt/e/wd/pipeline/6_output.bam/${var_sam}.output.bam
				
				# HaplotypeCaller
				/home/lee/wd/program/gatk-4.1.9.0/gatk --java-options "-Xmx4g" HaplotypeCaller \
				-R /mnt/e/wd/resource_bundle/human_g1k_v37.fasta \
				-I /mnt/e/wd/pipeline/6_output.bam/${var_sm}.output.bam \
				-O /mnt/e/wd/pipeline/7_gvcf/${var_sm}.g.vcf.gz \
				-ERC GCVF

				echo "Finish ${var_sm} pre-processing"
			fi
		done
	done
done
